name: compile source

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt update && sudo apt upgrade && sudo apt install -y build-essential libncurses6-dev libncursesw6-dev

      - name: compile hibou
        run: make

      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: hibou
          path: bin/hibou
