name: build RPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    container: centos:latest

    steps:
      - name: Install RPM Build Tools
        run: sudo yum install -y rpm-build rpmdevtools make gcc ncurses-devel

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up RPM Build Environment
        run: rpmdev-setuptree && cp hibou.spec ~/rpmbuild/SPECS/.

      - name: Create Source Tarball
        run: |
          mkdir ../hibou-1.0 && cp -r * ../hibou-1.0/.
          tar czvf ~/rpmbuild/SOURCES/hibou-1.0.tar.gz ../hibou-1.0

      - name: Build RPM Package
        run: rpmbuild -bb ~/rpmbuild/SPECS/hibou.spec

      - name: Upload RPM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hibou-rpm
          path: ~/rpmbuild/RPMS/**/*.rpm
